dist: trusty
language: node_js
node_js:
  - "lts/*"
before_install:
    - mkdir -p public/template
    - mkdir -p public/orange
    - mkdir -p public/automation
    - mkdir -p public/ansible
    - mkdir -p public/python
    - mv index.html public/
install: true
script:
    - cd template
    - npm install --global grunt 
    - npm install --global bower
    - npm install
    - bower install
    - grunt dist
    - cd ..
    - mv template/dist/* public/template

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master