dist: trusty
language: node_js
node_js:
  - "lts/*"
before_install:
    - mkdir -p public/automation
    - mkdir -p public/ansible
    - mkdir -p public/python
    - mv index.html public/
install: true
script:
    - cd automation
    - npm install --global grunt 
    - npm install --global bower
    - npm install
    - bower install
    - grunt dist
    - cd ..
    - mv automation/dist/* public/automation

    - cd ansible
    - npm install --global grunt 
    - npm install --global bower
    - npm install
    - bower install
    - grunt dist
    - cd ..
    - mv ansible/dist/* public/ansible

    - cd python
    - npm install --global grunt 
    - npm install --global bower
    - npm install
    - bower install
    - grunt dist
    - cd ..
    - mv python/dist/* public/python

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master